version: '3'
services:
  node:
    image: node:14-buster
    volumes:
      - ../:/home
    depends_on:
      - database
    command: ["/home/docker/wait-for-it.sh", "database:5432", "--", "/home/docker/run_tests.sh"]
  database:
    image: postgres:11
    volumes:
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
      - ./setup_db.sql:/run/setup_db.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
